var data = [
	{	
		"id": "1",
		"businessname": "Eget Odio Company",
		"firstname": "Bevis",
		"lastname": "Dean",
		"email": "Vestibulum@telluslorem.ca",
		"description": "penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc",
		"postcode": "1016 HZ",
		"streetname": "Prinsengracht 354",
		"lat": "52.368067",
		"lng": "4.882161",
		"city": "Amsterdam",
		"repairtype": "smart home installation",
		"imageUrl": "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
	},
	{
		"id": "2",
		"businessname": "Non Corporation",
		"firstname": "Renee",
		"lastname": "Middleton",
		"email": "feugiat.tellus.lorem@gravidamaurisut.net",
		"description": "tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id,",
		"postcode": "1018 MR",
		"streetname": "Oostenburgervoorstraat 72",
		"lat": "52.369787",
		"lng": "4.924680",
		"city": "Amsterdam",
		"repairtype": "Choe maker",
		"imageUrl": "./shop-img/shop2"
	},
	{
		"id": "3",
		"businessname": "Lectus Ante Dictum Institute",
		"firstname": "Aristotle",
		"lastname": "Strong",
		"email": "a.enim.Suspendisse@sodalesatvelit.com",
		"description": "leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit",
		"postcode": "1018 WA",
		"streetname": "Jacob Burggraafstraat 52",
		"lat": "52.372204",
		"lng": "4.922217",
		"city": "Amsterdam",
		"repairtype": "computer repair",
		"imageUrl": "./shop-img/shop3"
	},
	{
		"id": "4",
		"businessname": "Suspendisse Sagittis Nullam Industries",
		"firstname": "Jelani",
		"lastname": "Bush",
		"email": "ridiculus.mus@dolor.com",
		"description": "scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus",
		"postcode": "1012 CB",
		"streetname": "Bethaniëndwarsstraat 94",
		"lat": "52.371566",
		"lng": "4.898038",
		"city": "Amsterdam",
		"repairtype": "carpenter",
		"imageUrl": "./shop-img/shop4"
	},
	{
		"id": "5",
		"businessname": "Erat Institute",
		"firstname": "Tatyana",
		"lastname": "Rosa",
		"email": "ut.quam@lobortistellusjusto.net",
		"description": "cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit",
		"postcode": "1018 KV",
		"streetname": "Grote Wittenburgerstraat 54",
		"lat": "52.371670",
		"lng": "4.921720",
		"city": "Amsterdam",
		"repairtype": " electrician  ",
		"imageUrl": "./shop-img/shop5"
	},
	{
		"id": "6",
		"businessname": "Integer Company",
		"firstname": "Rosalyn",
		"lastname": "Watkins",
		"email": "risus@nislelementum.edu",
		"description": "natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut",
		"postcode": "1015 KP",
		"streetname": "Karthuizersdwarsstraat 106",
		"lat": "52.378833",
		"lng": "4.881280",
		"city": "Amsterdam",
		"repairtype": " bike painter ",
		"imageUrl": "./shop-img/shop6"
	},
	{
		"id": "7",
		"businessname": "Nec Consulting",
		"firstname": "Elmo",
		"lastname": "Gutierrez",
		"email": "mus.Proin@sedfacilisis.edu",
		"description": "lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc",
		"postcode": "1012 HH",
		"streetname": "Pijlsteeg 53",
		"lat": "52.372204",
		"lng": "4.895565",
		"city": "Amsterdam",
		"repairtype": "appliances repair ",
		"imageUrl": "./shop-img/shop7"
	},
	{
		"id": "8",
		"businessname": "Nisi Foundation",
		"firstname": "Garrett",
		"lastname": "Boyer",
		"email": "erat.Sed@Nuncmauris.ca",
		"description": "suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci",
		"postcode": "1018 HP",
		"streetname": "Boulevardpad 80",
		"lat": "52.368831",
		"lng": "4.923509",
		"city": "Amsterdam",
		"repairtype": "carpenter",
		"imageUrl": "./shop-img/shop8"
	},
	{
		"id": "9",
		"businessname": "Sociis LLP",
		"firstname": "Mannix",
		"lastname": "Sandoval",
		"email": "dolor.Fusce.feugiat@elementumsem.org",
		"description": "Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec",
		"postcode": "1012 HL",
		"streetname": "Pieter Jacobszstraat 78",
		"lat": "52.371659",
		"lng": "4.894835",
		"city": "Amsterdam",
		"repairtype": "computer repair",
		"imageUrl": "./shop-img/shop9"
	},
	{
		"id": "10",
		"businessname": "Eu Inc.",
		"firstname": "Darrel",
		"lastname": "Key",
		"email": "elit.a@adipiscing.co.uk",
		"description": "Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus",
		"postcode": "1012 HL",
		"streetname": "Valkensteeg 79",
		"lat": "52.373590",
		"lng": "4.892938",
		"city": "Amsterdam",
		"repairtype": "computer repair",
		"imageUrl": "./shop-img/shop10"
	} 
	
]

module.exports = data